user root;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Headers globais
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Connection "";

    # Server default
    server {
        listen 80;
        server_name _;

        location / {
            return 404 "Host não configurado";
        }
    }

    # logger do compressor
    server {
        listen 80;
        server_name compressor.home;

        charset utf-8;

        location = / {
            default_type text/html;

            return 200 '
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8">
    <style>
    body {
        font-family: monospace;
        white-space: pre;
        margin: 0;
        padding: 10px;
        background: #111;
        color: #0f0;
    }
    </style>
    </head>
    <body>
    Carregando log...
    <script>
    async function loadLog() {
        const res = await fetch("/log?" + Date.now());
        const text = await res.text();
        document.body.innerText = text.split("\\n").reverse().join("\\n");
    }

    setInterval(loadLog, 2000);
    loadLog();
    </script>
    </body>
    </html>';
        }

        location = /log {
            alias /data/data/com.termux/files/home/auto_compress.log;
            default_type text/plain;
            add_header Cache-Control no-cache;
        }
    }

    # Sonarr
    server {
        listen 80;
        server_name sonarr.home;

        location / {
            proxy_pass http://127.0.0.1:8989/;
        }
    }

    # Dashboard com glance
    server {
        listen 80;
        server_name dashboard.home;

        location / {
            proxy_pass http://127.0.0.1:8181/;
        }
    }

    # Radarr
    server {
        listen 80;
        server_name radarr.home;

        location / {
            proxy_pass http://127.0.0.1:7878/;
        }
    }

    # Prowlarr
    server {
        listen 80;
        server_name prowlarr.home;

        location / {
            proxy_pass http://127.0.0.1:9696/;
        }
    }

    # Bazarr
    server {
        listen 80;
        server_name bazarr.home;

        location / {
            proxy_pass http://127.0.0.1:6767/;
        }
    }

    # Jellyfin
    server {
        listen 80;
        server_name jellyfin.home;

        location / {
            proxy_pass http://127.0.0.1:8096/;
        }
    }

    # qBittorrent
    server {
        listen 80;
        server_name qbittorrent.home;

        location / {
            proxy_pass http://127.0.0.1:8080/;
        }
    }
}
